language: node_js
node_js: node
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  # - npm test
  - npx semantic-release
env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master

after_success:
  # - ./deploy.sh # TODO(you): deploy the PR changes to your staging server.
  - npm run lh -- https://react-map-app.netlify.com/
